// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

function evolve(_state, $$event) {
  return /* Registered */{
          _0: $$event._0
        };
}

var User_already_registered = /* @__PURE__ */Caml_exceptions.create("UserDecider.User_already_registered");

function decide(state, command) {
  if (state) {
    throw {
          RE_EXN_ID: User_already_registered,
          Error: new Error()
        };
  }
  return [/* UserRegistered */{
            _0: command._0
          }];
}

var initialState = /* Initial */0;

export {
  initialState ,
  evolve ,
  User_already_registered ,
  decide ,
  
}
/* No side effect */
